# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_response <- function(good, eta, y, mu, mu_eta_val) {
    .Call(`_bvs_compute_response`, good, eta, y, mu, mu_eta_val)
}

compute_weights <- function(good, weights, mu_eta_val, mu, varmu) {
    .Call(`_bvs_compute_weights`, good, weights, mu_eta_val, mu, varmu)
}

identity_mu_eta <- function(eta, eta_val) {
    invisible(.Call(`_bvs_identity_mu_eta`, eta, eta_val))
}

logit_mu_eta <- function(eta, eta_val) {
    invisible(.Call(`_bvs_logit_mu_eta`, eta, eta_val))
}

logit_deviance <- function(y, mu, wt) {
    .Call(`_bvs_logit_deviance`, y, mu, wt)
}

logit_linkinv <- function(eta, mu) {
    invisible(.Call(`_bvs_logit_linkinv`, eta, mu))
}

new_table <- function(i) {
    .Call(`_bvs_new_table`, i)
}

set_element_in_table <- function(key, value, table) {
    invisible(.Call(`_bvs_set_element_in_table`, key, value, table))
}

get_element_from_table <- function(key, table) {
    .Call(`_bvs_get_element_from_table`, key, table)
}

